version: '3'
services:
 mysql:
  image: mysql:8
  environment:
   MYSQL_DATABASE: 'rss-db'
   MYSQL_USER: 'admin'
   MYSQL_PASSWORD: 'admin'
   MYSQL_ROOT_PASSWORD: 'admin'
  ports:
   - "3306:3306"
  volumes:
   - mysql_volume:/var/lib/mysql
  networks:
   - local-net
  healthcheck:
   test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
   timeout: 20s
   retries: 10
 api:
  links:
  - db
  container_name: "api"
  build: ./
  ports:
  - "80:80"
  volumes:
  - ./code:/usr/src/server
  networks:
  - local-net
  depends_on:
    mysql:
     condition: service_healthy
networks:
  local-net:
    driver: bridge
volumes:
 mysql_volume: